#Dependencies
FROM node:21-alpine3.19 as deps

WORKDIR /usr/src/app

COPY package.json ./
COPY package-lock.json ./

RUN npm install


# Builder
FROM node:21-alpine3.19 as build

WORKDIR /usr/src/app

##Copy all the deps, node modules
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY . .

#RUN npm run test

RUN npm run build

RUN npm ci -f --only=production && npm cache clean --force

#RUN npx prisma migrate deploy
RUN npx prisma generate


# Create the last image
FROM node:21-alpine3.19 as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules

## Copy dist folder
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/prisma ./prisma

#Optional
ENV NODE_ENV=production

#Change username with limited privileges
USER node

EXPOSE 3000

CMD [ "node", "dist/main.js" ]